export const traducoes = {
    "HomePage.header.title": "Olá {name}",
    "HomePage.header.subtitle": "Bem-vindo ao seu painel de administração",
    "HomePage.widget.loading": "Carregando conteúdo do widget",
    "HomePage.widget.error": "Não foi possível carregar o conteúdo do widget.",
    "HomePage.widget.no-data": "Nenhum conteúdo encontrado.",
    "HomePage.widget.no-permissions": "Você não tem permissão para ver este widget",
    "Settings.apiTokens.copy.lastWarning": "Copie seu token de API",
    "Settings.apiTokens.ListView.headers.createdAt": "Criado em",
    "Settings.apiTokens.ListView.headers.description": "Descrição",
    "Settings.apiTokens.ListView.headers.lastUsedAt": "Último uso",
    "Settings.apiTokens.ListView.headers.name": "Nome",
    "Settings.apiTokens.ListView.headers.type": "Tipo de token",
    "Settings.apiTokens.createPage.BoundRoute.title": "Rota vinculada a",
    "Settings.apiTokens.createPage.permissions.description": "Somente ações vinculadas por uma rota estão listadas abaixo.",
    "Settings.apiTokens.createPage.permissions.header.hint": "Selecione as ações da aplicação ou do plugin e clique no ícone da engrenagem para exibir a rota vinculada",
    "Settings.apiTokens.createPage.permissions.header.title": "Configurações avançadas",
    "Settings.apiTokens.createPage.permissions.title": "Permissões",
    "Settings.apiTokens.createPage.title": "Criar Token de API",
    "Settings.apiTokens.regenerate": "Regenerar",
    "Settings.apiTokens.lastHour": "última hora",
    "Settings.application.customization.auth-logo.carousel-hint": "Substitua o logo nas páginas de autenticação",
    "Settings.application.customization.carousel.auth-logo.title": "Logo de autenticação",
    "Settings.application.customization.carousel.menu-logo.title": "Logo do menu",
    "Settings.application.customization.menu-logo.carousel-hint": "Substitua o logo na navegação principal",
    "Settings.application.customization.size-details": "Dimensão máxima: {dimension}×{dimension}, Tamanho máximo do arquivo: {size}KB",
    "Settings.application.ee-or-ce": "{communityEdition, select, true {Edição Comunitária} other {Edição Empresarial}}",
    "Settings.application.ee.admin-seats.add-seats": "Gerenciar assentos",
    "Settings.application.ee.admin-seats.support": "Contatar vendas",
    "Settings.application.ee.admin-seats.at-limit-tooltip": "No limite: adicione assentos para convidar mais usuários",
    "Settings.application.ee.admin-seats.count": "<text>{enforcementUserCount}</text>/{permittedSeats}",
    "Settings.permissions.auditLogs.action": "Ação",
    "Settings.permissions.auditLogs.admin.auth.success": "Login de admin",
    "Settings.permissions.auditLogs.admin.logout": "Logout de admin",
    "Settings.permissions.auditLogs.component.create": "Criar componente",
    "Settings.permissions.auditLogs.component.delete": "Excluir componente",
    "Settings.permissions.auditLogs.component.update": "Atualizar componente",
    "Settings.permissions.auditLogs.content-type.create": "Criar tipo de conteúdo",
    "Settings.permissions.auditLogs.content-type.delete": "Excluir tipo de conteúdo",
    "Settings.permissions.auditLogs.content-type.update": "Atualizar tipo de conteúdo",
    "Settings.permissions.auditLogs.date": "Data",
    "Settings.permissions.auditLogs.details": "Detalhes do log",
    "Settings.permissions.auditLogs.entry.create": "Criar entrada{model, select, undefined {} other { ({model})}}",
    "Settings.permissions.auditLogs.entry.delete": "Excluir entrada{model, select, undefined {} other { ({model})}}",
    "Settings.permissions.auditLogs.entry.publish": "Publicar entrada{model, select, undefined {} other { ({model})}}",
    "Settings.permissions.auditLogs.entry.unpublish": "Despublicar entrada{model, select, undefined {} other { ({model})}}",
    "Settings.permissions.auditLogs.entry.update": "Atualizar entrada{model, select, undefined {} other { ({model})}}",
    "Settings.permissions.auditLogs.filters.combobox.aria-label": "Pesquise e selecione uma opção para filtrar",
    "Settings.permissions.auditLogs.listview.header.subtitle": "Registros de todas as atividades que ocorreram no seu ambiente",
    "Settings.permissions.auditLogs.not-available": "Logs de auditoria estão disponíveis apenas em um plano pago. Atualize para obter uma visualização pesquisável e filtrável de todas as atividades.",
    "Settings.permissions.auditLogs.media.create": "Criar mídia",
    "Settings.permissions.auditLogs.media.delete": "Excluir mídia",
    "Settings.permissions.auditLogs.media.update": "Atualizar mídia",
    "Settings.permissions.auditLogs.payload": "Payload",
    "Settings.permissions.auditLogs.permission.create": "Criar permissão",
    "Settings.permissions.auditLogs.permission.delete": "Excluir permissão",
    "Settings.permissions.auditLogs.permission.update": "Atualizar permissão",
    "Settings.permissions.auditLogs.role.create": "Criar papel",
    "Settings.permissions.auditLogs.role.delete": "Excluir papel",
    "Settings.permissions.auditLogs.role.update": "Atualizar papel",
    "Settings.permissions.auditLogs.user": "Usuário",
    "Settings.permissions.auditLogs.user.create": "Criar usuário",
    "Settings.permissions.auditLogs.user.delete": "Excluir usuário",
    "Settings.permissions.auditLogs.user.fullname": "{firstname} {lastname}",
    "Settings.permissions.auditLogs.user.update": "Atualizar usuário",
    "Settings.permissions.auditLogs.userId": "ID do Usuário",
    "Settings.permissions.conditions.define-conditions": "Definir condições",
    "Settings.permissions.users.active": "Ativo",
    "Settings.permissions.users.sso.provider.error": "Ocorreu um erro ao solicitar as configurações de SSO",
    "Settings.permissions.users.inactive": "Inativo",
    "Settings.permissions.users.roles": "Papéis",
    "Settings.permissions.users.strapi-author": "Autor",
    "Settings.permissions.users.strapi-editor": "Editor",
    "Settings.permissions.users.strapi-super-admin": "Super Admin",
    "Settings.permissions.users.user-status": "Status do usuário",
    "Settings.permissions.users.username": "Nome de usuário",
    "Settings.profile.form.section.experience.mode.option-system-label": "Usar configurações do sistema",
    "Settings.sso.form.localAuthenticationLock.label": "Bloqueio de autenticação local",
    "Settings.sso.form.localAuthenticationLock.description": "Selecione os papéis para os quais deseja desabilitar a autenticação local",
    "Settings.sso.not-available": "SSO está disponível apenas em um plano pago. Atualize para configurar métodos adicionais de login e registro para o painel de administração.",
    "Settings.content-history.title": "Histórico de Conteúdo",
    "Settings.content-history.description": "Tenha mais controle sobre cada etapa do ciclo de vida do seu conteúdo.",
    "Settings.content-history.not-available": "Histórico de Conteúdo está disponível apenas em um plano pago. Atualize para obter controle total sobre o ciclo de vida do conteúdo.",
    "Settings.tokens.Button.cancel": "Cancelar",
    "Settings.tokens.Button.regenerate": "Regenerar",
    "Settings.tokens.ListView.headers.createdAt": "Criado em",
    "Settings.tokens.ListView.headers.description": "Descrição",
    "Settings.tokens.ListView.headers.lastUsedAt": "Último uso",
    "Settings.tokens.ListView.headers.name": "Nome",
    "Settings.tokens.RegenerateDialog.title": "Regenerar token",
    "Settings.tokens.copy.title": "Token",
    "Settings.tokens.duration.30-days": "30 dias",
    "Settings.tokens.duration.7-days": "7 dias",
    "Settings.tokens.duration.90-days": "90 dias",
    "Settings.tokens.duration.expiration-date": "Data de expiração",
    "Settings.tokens.duration.unlimited": "Ilimitado",
    "Settings.tokens.form.description": "Descrição",
    "Settings.tokens.form.duration": "Duração do token",
    "Settings.tokens.form.name": "Nome",
    "Settings.tokens.form.type": "Tipo de token",
    "Settings.tokens.popUpWarning.message": "Tem certeza de que deseja regenerar este token?",
    "Settings.tokens.regenerate": "Regenerar",
    "Settings.tokens.types.custom": "Personalizado",
    "Settings.transferTokens.ListView.headers.type": "Tipo de token",
    "Settings.transferTokens.addFirstToken": "Adicione seu primeiro Transfer Token",
    "Settings.transferTokens.addNewToken": "Adicionar novo Transfer Token",
    "Settings.transferTokens.create": "Criar novo Transfer Token",
    "Settings.transferTokens.createPage.title": "Criar Transfer Token",
    "Settings.transferTokens.description": "Lista de tokens de transferência gerados",
    "Settings.transferTokens.emptyStateLayout": "Você ainda não tem nenhum conteúdo...",
    "Settings.transferTokens.title": "Transfer Tokens",
    "Settings.webhooks.event.select": "Selecionar evento",
    "Settings.webhooks.events.isLoading": "Carregando eventos",
    "Settings.webhooks.events.delete": "Excluir webhook",
    "Settings.webhooks.list.loading.success": "Webhooks carregados com sucesso",
    "Settings.webhooks.validation.name.required": "Nome é obrigatório",
    "Settings.webhooks.validation.name.regex": "O nome deve começar com uma letra e conter apenas letras, números, espaços e underscores",
    "Settings.webhooks.validation.url.required": "Url é obrigatório",
    "Settings.webhooks.validation.url.regex": "O valor deve ser uma Url válida",
    "Settings.webhooks.validation.key": "Chave é obrigatória",
    "Settings.webhooks.validation.value": "Valor é obrigatório",
    "Settings.page.PurchaseAudit-logs.description": "Acompanhe e revise alterações com sua equipe",
    "Settings.page.PurchaseAudit-logs.perks1": "Acompanhe alterações facilmente",
    "Settings.page.PurchaseAudit-logs.perks2": "Revise mudanças com facilidade",
    "Settings.page.PurchaseAudit-logs.perks3": "Mantenha segurança e conformidade",
    "Settings.page.PurchaseContent-history.description": "Reverta alterações de conteúdo instantaneamente",
    "Settings.page.PurchaseContent-history.perks1": "Navegue pelo histórico de conteúdo",
    "Settings.page.PurchaseContent-history.perks2": "Reverta mudanças com um clique",
    "Settings.page.PurchaseContent-history.perks3": "Acompanhe alterações entre idiomas",
    "Settings.page.PurchaseSSO.description": "Simplifique a autenticação da sua equipe",
    "Settings.page.PurchaseSSO.perks1": "Autenticação unificada",
    "Settings.page.PurchaseSSO.perks2": "Segurança aprimorada",
    "Settings.page.PurchaseSSO.perks3": "Suporte para webhooks",
    "Settings.page.purchase.upgrade.cta": "Atualizar",
    "Settings.page.purchase.learn-more.cta": "Saiba mais",
    "admin.pages.MarketPlacePage.sort.label": "Ordenar por",
    "admin.pages.MarketPlacePage.filters.categories": "Categorias",
    "admin.pages.MarketPlacePage.filters.categoriesSelected": "{count, plural, =0 {Nenhuma categoria} one {# categoria} other {# categorias}} selecionadas",
    "admin.pages.MarketPlacePage.filters.collections": "Coleções",
    "admin.pages.MarketPlacePage.filters.collectionsSelected": "{count, plural, =0 {Nenhuma coleção} one {# coleção} other {# coleções}} selecionadas",
    "admin.pages.MarketPlacePage.plugin.downloads": "Este plugin possui {downloadsCount} downloads semanais",
    "admin.pages.MarketPlacePage.plugin.githubStars": "Este plugin foi estrelado {starsCount} vezes no GitHub",
    "admin.pages.MarketPlacePage.plugin.version": "Atualize sua versão do Strapi: \"{strapiAppVersion}\" para: \"{versionRange}\"",
    "admin.pages.MarketPlacePage.plugin.version.null": "Não foi possível verificar a compatibilidade com sua versão do Strapi: \"{strapiAppVersion}\"",
    "admin.pages.MarketPlacePage.provider.downloads": "Este provedor possui {downloadsCount} downloads semanais",
    "admin.pages.MarketPlacePage.provider.githubStars": "Este provedor foi estrelado {starsCount} vezes no GitHub",
    "admin.pages.MarketPlacePage.sort.alphabetical": "Ordem alfabética",
    "admin.pages.MarketPlacePage.sort.alphabetical.selected": "Ordenar por ordem alfabética",
    "admin.pages.MarketPlacePage.sort.githubStars": "Número de estrelas no GitHub",
    "admin.pages.MarketPlacePage.sort.githubStars.selected": "Ordenar por estrelas no GitHub",
    "admin.pages.MarketPlacePage.sort.newest": "Mais recentes",
    "admin.pages.MarketPlacePage.sort.newest.selected": "Ordenar por mais recentes",
    "admin.pages.MarketPlacePage.sort.npmDownloads": "Número de downloads",
    "admin.pages.MarketPlacePage.sort.npmDownloads.selected": "Ordenar por downloads do npm",
    "noPreview": "semPreview",
    "app.component.table.read": "Ler {target}",
    "app.component.table.view": "Detalhes de {target}",
    "app.components.BlockLink.cloud": "Strapi Cloud",
    "app.components.BlockLink.cloud.content": "Hospedagem em nuvem totalmente gerenciada para seu projeto Strapi.",
    "app.components.FreeTrialEndedModal.button.downgrade": "Rebaixar para Comunidade",
    "app.components.FreeTrialEndedModal.button.upgrade": "Permanecer no plano Growth",
    "app.components.FreeTrialEndedModal.description": "Seu acesso a recursos do plano Growth como Histórico de Conteúdo, Lançamentos e Single Sign-On (SSO) expirou.",
    "app.components.FreeTrialEndedModal.notice.item1": "Ao rebaixar você perderá acesso aos recursos acima.",
    "app.components.FreeTrialEndedModal.notice.item2": "O histórico de versões de documentos será excluído.",
    "app.components.FreeTrialEndedModal.notice.item3": "Todos os lançamentos serão apagados.",
    "app.components.FreeTrialEndedModal.notice.item4": "Se você rebaixar, certifique-se de definir uma senha de admin raiz para manter o acesso ao painel.",
    "app.components.FreeTrialEndedModal.notice.title": "Importante saber:",
    "app.components.FreeTrialEndedModal.title": "Seu período de teste terminou",
    "app.components.FreeTrialWelcomeModal.button": "Começar a explorar",
    "app.components.FreeTrialWelcomeModal.description1": "Nos próximos 30 dias, você terá acesso total a recursos avançados como Histórico de Conteúdo, Lançamentos e Single Sign-On (SSO) – tudo o que precisa para explorar o poder do Strapi CMS.",
    "app.components.FreeTrialWelcomeModal.description2": "Aproveite este tempo para construir, personalizar e testar seus fluxos de conteúdo com total flexibilidade!",
    "app.components.FreeTrialWelcomeModal.title": "Estamos felizes em ter você a bordo",
    "app.components.LeftMenu.trialCountdown.endedAt": "Seu período de teste terminou em {date}.",
    "app.components.LeftMenu.trialCountdown.endsAt": "Seu período de teste termina em {date}.",
    "app.components.NpsSurvey.banner-title": "Quão provável é você recomendar o Strapi a um amigo ou colega?",
    "app.components.NpsSurvey.feedback-response": "Muito obrigado pelo seu feedback!",
    "app.components.NpsSurvey.feedback-question": "Você tem alguma sugestão de melhoria?",
    "app.components.NpsSurvey.submit-feedback": "Enviar Feedback",
    "app.components.NpsSurvey.dismiss-survey-label": "Descartar pesquisa",
    "app.components.NpsSurvey.no-recommendation": "Nada provável",
    "app.components.NpsSurvey.happy-to-recommend": "Muito provável",
    "app.components.NpsSurvey.select-rating": "Selecione a avaliação",
    "app.components.Onboarding.link.build-content": "Construa uma arquitetura de conteúdo",
    "app.components.Onboarding.link.manage-content": "Adicionar e gerenciar conteúdo",
    "app.components.Onboarding.link.manage-media": "Gerenciar mídia",
    "app.components.Onboarding.link.more-videos": "Assistir mais vídeos",
    "app.components.ToggleCheckbox.enabled-label": "Ativado",
    "app.components.ToggleCheckbox.disabled-label": "Desativado",
    "app.components.UpsellBanner.button": "Atualize agora",
    "app.components.UpsellBanner.intro": "Acesso a recursos do plano Growth:",
    "app.components.UpsellBanner.text": "Como parte do seu teste, você pode explorar ferramentas premium como Histórico de Conteúdo, Lançamentos e Single Sign-On (SSO).",
    "app.utils.delete": "Excluir",
    "app.utils.refresh": "Atualizar",
    "app.utils.published": "Publicado",
    "app.utils.ready-to-publish": "Pronto para publicar",
    "app.utils.already-published": "Já publicado",
    "app.utils.ready-to-publish-changes": "Pronto para publicar alterações",
    "app.utils.ready-to-unpublish-changes": "Pronto para despublicar",
    "app.confirm.body": "Tem certeza?",
    "components.Input.error.contain.maxBytes": "A senha deve ter menos de 73 bytes",
    "components.Input.error.validation.combobox.invalid": "O valor fornecido não é válido",
    "components.Input.error.validation.string": "Isto não é uma string válida.",
    "components.Input.error.validation.email.withField": "{field} é um e-mail inválido",
    "components.Input.error.validation.json.withField": "{field} não corresponde ao formato JSON",
    "components.Input.error.validation.lowercase.withField": "{field} deve ser uma string em minúsculas",
    "components.Input.error.validation.max.withField": "{field} é muito alto.",
    "components.Input.error.validation.maxLength.withField": "{field} é muito longo.",
    "components.Input.error.validation.min.withField": "{field} é muito baixo.",
    "components.Input.error.validation.minLength.withField": "{field} é muito curto.",
    "components.Input.error.validation.minSupMax.withField": "{field} não pode ser superior",
    "components.Input.error.validation.regex.withField": "{field} não corresponde à expressão regular.",
    "components.Input.error.validation.required.withField": "{field} é obrigatório.",
    "components.Input.error.validation.unique.withField": "{field} já está em uso.",
    "components.ViewSettings.tooltip": "Configurações de visualização",
    "components.Blocks.modifiers.bold": "Negrito",
    "components.Blocks.modifiers.italic": "Itálico",
    "components.Blocks.modifiers.underline": "Sublinhado",
    "components.Blocks.modifiers.strikethrough": "Tachado",
    "components.Blocks.modifiers.code": "Código inline",
    "components.Blocks.link": "Link",
    "components.Blocks.expand": "Expandir",
    "components.Blocks.collapse": "Recolher",
    "components.Blocks.popover.text": "Texto",
    "components.Blocks.popover.text.placeholder": "Digite o texto do link",
    "components.Blocks.popover.link": "Link",
    "components.Blocks.popover.link.placeholder": "Cole o link",
    "components.Blocks.popover.link.rel": "Rel (opcional)",
    "components.Blocks.popover.link.rel.placeholder": "noopener, nofollow, noreferrer",
    "components.Blocks.popover.link.target": "Target (opcional)",
    "components.Blocks.popover.link.target.placeholder": "_blank, _self, _parent, _top",
    "components.Blocks.popover.link.error": "Digite um link válido",
    "components.Blocks.popover.remove": "Remover",
    "components.Blocks.popover.edit": "Editar",
    "components.Blocks.blocks.selectBlock": "Selecione um bloco",
    "components.Blocks.blocks.text": "Texto",
    "components.Blocks.blocks.heading1": "Título 1",
    "components.Blocks.blocks.heading2": "Título 2",
    "components.Blocks.blocks.heading3": "Título 3",
    "components.Blocks.blocks.heading4": "Título 4",
    "components.Blocks.blocks.heading5": "Título 5",
    "components.Blocks.blocks.heading6": "Título 6",
    "components.Blocks.blocks.code": "Bloco de código",
    "components.Blocks.blocks.quote": "Citação",
    "components.Blocks.blocks.image": "Imagem",
    "components.Blocks.blocks.unorderedList": "Lista com marcadores",
    "components.Blocks.blocks.orderedList": "Lista numerada",
    "components.Blocks.blocks.code.languageLabel": "Selecione uma linguagem",
    "components.Blocks.dnd.instruction": "Para reorganizar os blocos, pressione Command ou Control junto com Shift e as setas para cima ou para baixo",
    "components.Blocks.dnd.reorder": "{item}, movido. Nova posição no editor: {position}.",
    "components.Wysiwyg.blocks.code": "Código",
    "components.premiumFeature.title": "Recurso premium",
    "global.auditLogs": "Logs de Auditoria",
    "global.close": "Fechar",
    "global.home": "Início",
    "global.error": "Algo deu errado",
    "global.last-change.redo": "Refazer última alteração",
    "global.last-change.undo": "Desfazer última alteração",
    "global.last-changes.discard": "Descartar últimas alterações",
    "global.more": "Mais",
    "global.new": "Novo",
    "global.profile.settings": "Configurações do perfil",
    "global.fullname": "{firstname} {lastname}",
    "global.learn-more": "Saiba mais",
    "notification.ee.warning.at-seat-limit.title": "{licenseLimitStatus, select, OVER_LIMIT {Acima do} AT_LIMIT {No}} limite de assentos ({currentUserCount}/{permittedSeats})",
    "notification.ee.warning.over-.message": "Adicione assentos para {licenseLimitStatus, select, OVER_LIMIT {convidar} AT_LIMIT {re-habilitar}} Usuários. Se você já fez isso mas ainda não aparece no Strapi, certifique-se de reiniciar sua aplicação.",
    "notification.error.invalid.configuration": "Você possui uma configuração inválida. Verifique o log do servidor para mais informações.",
    "notification.error.tokennamenotunique": "Nome já atribuído a outro token",
    "notification.success.apitokencreated": "Token de API criado com sucesso",
    "notification.success.apitokenedited": "Token de API editado com sucesso",
    "notification.success.transfertokencreated": "Transfer Token criado com sucesso",
    "notification.success.transfertokenedited": "Transfer Token editado com sucesso",
    "selectButtonTitle": "selecionarTítuloDoBotão",
    "tours.contentTypeBuilder.Introduction.title": "Bem-vindo ao Content-Type Builder!",
    "tours.contentTypeBuilder.Introduction.content": "Aqui você cria e gerencia a estrutura do seu app com tipos de coleção, tipos únicos e componentes reutilizáveis. Vamos começar!",
    "tours.contentTypeBuilder.AIChat.title": "Hora de começar!",
    "tours.contentTypeBuilder.AIChat.content": "<p>Se tiver alguma dúvida sobre o Content-Type Builder ou o Strapi, pergunte aqui.</p><p>O Strapi AI pode gerar esquemas personalizados para suas necessidades. Peça exatamente o que quiser, por exemplo:<ul><li>Seletor de data</li><li>Campos de e-mail e senha</li><li>Mídia de qualquer tipo</li><li>UIDs</li></ul></p><p>Não tenha vergonha, experimente!</p>",
    "tours.contentTypeBuilder.CollectionTypes.title": "Tipos de Coleção",
    "tours.contentTypeBuilder.CollectionTypes.content": "Use-os para gerenciar múltiplas entradas — como postagens de blog ou produtos.",
    "tours.contentTypeBuilder.SingleTypes.title": "Tipos Únicos",
    "tours.contentTypeBuilder.SingleTypes.content": "Perfeito para entradas únicas como sua página inicial ou configurações do site.",
    "tours.contentTypeBuilder.Components.title": "Componentes",
    "tours.contentTypeBuilder.Components.content": "Crie uma vez, reutilize em qualquer lugar. Use componentes para itens como botões, cards ou sliders.",
    "tours.contentTypeBuilder.YourTurn.title": "Sua vez — Crie algo!",
    "tours.contentTypeBuilder.YourTurn.content": "Crie um tipo de coleção ou um tipo único. Clique no botão \"+\", escolha um nome, clique em \"Continuar\" e nós guiaremos o restante do processo.",
    "tours.contentTypeBuilder.AddFields.title": "Adicione um campo",
    "tours.contentTypeBuilder.AddFields.content": "Comece adicionando seu primeiro campo — como nome, imagem ou relação. Seu tipo de conteúdo precisa ter forma antes de poder armazenar dados.",
    "tours.contentTypeBuilder.Save.title": "Não saia sem salvar!",
    "tours.contentTypeBuilder.Save.content": "Clique em \"Salvar\" para registrar seu tipo de conteúdo e evitar perder seu trabalho. Quase lá!",
    "tours.contentTypeBuilder.Finish.title": "Primeiro passo concluído! 🎉",
    "tours.contentTypeBuilder.Finish.content": "Você criou seu primeiro tipo de conteúdo! Agora vá até o Content Manager para começar a adicionar entradas!",
    "tours.apiTokens.Introduction.title": "Por fim, tokens de API",
    "tours.apiTokens.Introduction.content": "Controle o acesso à API com permissões altamente personalizáveis.",
    "tours.apiTokens.ManageAPIToken.title": "Gerenciar um token de API",
    "tours.apiTokens.ManageAPIToken.content": "Clique no ícone de lápis para ver e atualizar um token de API existente.",
    "tours.apiTokens.ViewAPIToken.title": "Ver token de API",
    "tours.apiTokens.ViewAPIToken.content": "Clique no botão \"Ver token\" para visualizar seu token de API.",
    "tours.apiTokens.CopyAPIToken.title": "Copie seu token de API",
    "tours.apiTokens.CopyAPIToken.content": "Clique no botão \"Copiar\" para salvar seu token de API, você precisará dele para fazer requisições à sua aplicação. {spacer} Ainda tem dúvidas? Saiba mais sobre <a>tokens de API</a>.",
    "tours.apiTokens.FinalStep.title": "Parabéns, é hora de implantar sua aplicação!",
    "tours.apiTokens.FinalStep.content": "Você tem tudo que precisa para implantar sua aplicação e compartilhar conteúdo com o mundo.",
    "tours.contentManager.Introduction.title": "Content Manager",
    "tours.contentManager.Introduction.content": "Crie e gerencie conteúdo a partir dos seus tipos de coleção e tipos únicos.",
    "tours.contentManager.CreateNewEntry.title": "Criar nova entrada",
    "tours.contentManager.CreateNewEntry.content": "Clique no botão \"Criar nova entrada\" para criar e publicar uma nova entrada para este tipo de coleção.",
    "tours.contentManager.Fields.title": "Campos",
    "tours.contentManager.Fields.content": "Primeiro, preencha os campos que você criou no Content-Type Builder.",
    "tours.contentManager.Publish.title": "Publicar",
    "tours.contentManager.Publish.content": "Depois clique no botão \"Publicar\" para tornar seu conteúdo disponível pela API.",
    "tours.contentManager.FinalStep.title": "Hora de configurar tokens de API!",
    "tours.contentManager.FinalStep.content": "Agora que você criou e publicou uma entrada, vamos configurar um token de API para gerenciar o acesso ao conteúdo.",
    "tours.stepCount": "Passo {currentStep} de {tourLength}",
    "tours.skip": "Pular",
    "tours.next": "Próximo",
    "tours.gotIt": "Entendi",
    "tours.overview.title": "Descubra sua aplicação!",
    "tours.overview.subtitle": "Siga o tour guiado para aproveitar ao máximo o Strapi.",
    "tours.overview.close": "Fechar tour guiado",
    "tours.overview.tasks": "Suas tarefas",
    "tours.overview.contentTypeBuilder.label": "Crie seu esquema",
    "tours.overview.contentManager.label": "Crie e publique conteúdo",
    "tours.overview.apiTokens.label": "Copiar um token de API",
    "tours.overview.strapiCloud.label": "Implante sua aplicação no Strapi Cloud",
    "tours.overview.strapiCloud.link": "Ler documentação",
    "tours.overview.tour.link": "Iniciar",
    "tours.overview.tour.done": "Concluído",
    "tours.overview.close.description": "Tem certeza que deseja fechar o tour guiado?",
    "tours.profile.title": "Tour guiado",
    "tours.profile.description": "Você pode redefinir o tour guiado a qualquer momento.",
    "tours.profile.reset": "Redefinir tour guiado",
    "tours.profile.notification.success.reset": "Tour guiado redefinido",
    "tours.overview.completed": "{completed}% concluído",
    "widget.key-statistics.title": "Estatísticas do projeto",
    "widget.key-statistics.list.admins": "Admins",
    "widget.key-statistics.list.apiTokens": "Tokens de API",
    "widget.key-statistics.list.assets": "Mídias",
    "widget.key-statistics.list.components": "Componentes",
    "widget.key-statistics.list.contentTypes": "Tipos de conteúdo",
    "widget.key-statistics.list.entries": "Entradas",
    "widget.key-statistics.list.locales": "Idiomas",
    "widget.key-statistics.list.webhooks": "Webhooks",
    "widget.last-activity.link": "Abrir Logs de Auditoria",
    "widget.last-activity.no-activity": "Nenhuma atividade",
    "widget.last-activity.title": "Última atividade",
    "widget.profile.title": "Perfil",
    "HomePage.addWidget.title": "Adicionar Widget",
    "HomePage.addWidget.noWidgetsAvailable": "Nenhum widget disponível para adicionar",
    "HomePage.addWidget.button": "Adicionar Widget",
    "HomePage.widget.delete": "Excluir",
    "HomePage.widget.drag": "Arraste para mover"
}