export default {
    config: {
        // Substitua estas URLs pelas suas imagens se quiser mudar o logo

        // Configuração de Traduções (Opcional)
        locales: ['pt-BR', 'en'],

        translations: {
            'pt-BR': {
                // 1. Personalização da Marca (O que já tínhamos)
                'Auth.form.welcome.title': 'Bem-vindo ao Painel da Insurgência',
                'Auth.form.welcome.subtitle': 'Faça login para gerenciar o conteúdo',
                'app.components.LeftMenu.navbrand.title': 'Insurgência',
                'app.components.LeftMenu.navbrand.workplace': 'Painel Administrativo',

                // 2. Correções de chaves faltando na Home (Comparado ao EN)
                'HomePage.header.title': 'Olá {name}',
                'HomePage.header.subtitle': 'Bem-vindo ao seu painel administrativo',
                'HomePage.widget.loading': 'Carregando widget',
                'HomePage.widget.error': 'Não foi possível carregar o widget.',
                'HomePage.widget.no-data': 'Nenhum conteúdo encontrado.',
                'HomePage.widget.no-permissions': 'Você não tem permissão para ver este widget',

                // 3. Pesquisa NPS (Faltava tudo no PT-BR)
                'app.components.NpsSurvey.banner-title': 'Qual a probabilidade de você recomendar o Strapi para um amigo ou colega?',
                'app.components.NpsSurvey.feedback-response': 'Muito obrigado pelo seu feedback!',
                'app.components.NpsSurvey.feedback-question': 'Você tem alguma sugestão de melhoria?',
                'app.components.NpsSurvey.submit-feedback': 'Enviar Feedback',
                'app.components.NpsSurvey.dismiss-survey-label': 'Dispensar pesquisa',
                'app.components.NpsSurvey.no-recommendation': 'Pouco provável',
                'app.components.NpsSurvey.happy-to-recommend': 'Extremamente provável',
                'app.components.NpsSurvey.select-rating': 'Selecione uma nota',

                // 4. Tokens de API (Faltavam as durações)
                'Settings.tokens.duration.7-days': '7 dias',
                'Settings.tokens.duration.30-days': '30 dias',
                'Settings.tokens.duration.90-days': '90 dias',
                'Settings.tokens.duration.unlimited': 'Ilimitado',
                'Settings.tokens.form.duration': 'Duração do Token',
                'Settings.tokens.RegenerateDialog.title': 'Regerar token',
                'Settings.tokens.popUpWarning.message': 'Tem certeza que deseja regerar este token?',

                // 5. Logs de Auditoria e Histórico (Muitos faltavam)
                'Settings.permissions.auditLogs.action': 'Ação',
                'Settings.permissions.auditLogs.date': 'Data',
                'Settings.permissions.auditLogs.user': 'Usuário',
                'Settings.permissions.auditLogs.payload': 'Carga (Payload)',
                'global.auditLogs': 'Logs de Auditoria',

                // 6. Configurações de Upload
                'app.components.InputFileDetails.originalName': 'Nome original:',
                'app.components.InputFileDetails.size': 'Tamanho:',
                'app.components.ImgPreview.hint': 'Arraste e solte arquivos ou clique para buscar',

                // 7. Correções gerais de botões
                'global.save': 'Salvar',
                'global.cancel': 'Cancelar',
                'global.delete': 'Excluir',
                'global.confirm': 'Confirmar',

                // CHAVES FALTANTES ADICIONADAS (do arquivo oficial PT-BR)
                'Analytics': 'Monitoramento',
                'Documentation': 'Documentação',
                'Email': 'E-mail',
                'Password': 'Senha',
                'Provider': 'Provedor',
                'ResetPasswordToken': 'Redefinir o token de senha',
                'Role': 'Função',
                'light': 'Claro',
                'dark': 'Escuro',
                'Username': 'Nome de usuário',
                'Users': 'Usuários',
                'anErrorOccurred': 'Ops! Algo deu errado. Por favor, tente novamente.',
                'clearLabel': 'Limpar',
                'or': 'OU',
                'skipToContent': 'Pular para o conteúdo',
                'submit': 'Enviar',

                // Auth Components
                'Auth.components.Oops.text': 'Sua conta foi suspensa.',
                'Auth.components.Oops.text.admin': 'Se isso foi um erro, por favor, contate seu administrador.',
                'Auth.components.Oops.title': 'Ops...',
                'Auth.form.active.label': 'Ativo',
                'Auth.form.button.forgot-password': 'Enviar e-mail',
                'Auth.form.button.go-home': 'VOLTAR PARA O INÍCIO',
                'Auth.form.button.login': 'Entrar',
                'Auth.form.button.login.providers.error': 'Não foi possível conectar você pelo provedor selecionado.',
                'Auth.form.button.login.strapi': 'Entrar com Strapi',
                'Auth.form.button.password-recovery': 'Recuperação de Senha',
                'Auth.form.button.register': 'Pronto para começar',
                'Auth.form.confirmPassword.label': 'Confirmação de senha',
                'Auth.form.currentPassword.label': 'Senha atual',
                'Auth.form.email.label': 'E-mail',
                'Auth.form.email.placeholder': 'kai@doe.com',
                'Auth.form.error.blocked': 'Sua conta foi bloqueada pelo administrador.',
                'Auth.form.error.code.provide': 'Código incorreto fornecido.',
                'Auth.form.error.confirmed': 'O email da sua conta não foi confirmado.',
                'Auth.form.error.email.invalid': 'Este email é inválido.',
                'Auth.form.error.email.provide': 'Por favor, forneça seu nome de usuário ou seu e-mail.',
                'Auth.form.error.email.taken': 'O email já foi utilizado',
                'Auth.form.error.invalid': 'Identificador ou senha inválida.',
                'Auth.form.error.params.provide': 'Params incorretos fornecidos.',
                'Auth.form.error.password.format': 'Sua senha não pode conter o símbolo` $ `mais de três vezes.',
                'Auth.form.error.password.local': 'Este usuário nunca definiu uma senha local, por favor faça o login através do provedor usado durante a criação da conta.',
                'Auth.form.error.password.matching': 'As senhas não coincidem.',
                'Auth.form.error.password.provide': 'Por favor, forneça sua senha',
                'Auth.form.error.ratelimit': 'Muitas tentativas, tente novamente em um minuto.',
                'Auth.form.error.user.not-exist': 'Este e-mail não existe.',
                'Auth.form.error.username.taken': 'Nome de usuário já foi obtido',
                'Auth.form.firstname.label': 'Primeiro nome',
                'Auth.form.firstname.placeholder': 'ex: Kai',
                'Auth.form.forgot-password.email.label': 'Digite seu email',
                'Auth.form.forgot-password.email.label.success': 'E-mail enviado com sucesso para',
                'Auth.form.lastname.label': 'Último nome',
                'Auth.form.lastname.placeholder': 'ex: Doe',
                'Auth.form.password.hide-password': 'Esconder senha',
                'Auth.form.password.hint': 'A senha deve conter pelo menos 8 caracteres, 1 letra maiúscula, 1 letra minúscula, e 1 número',
                'Auth.form.password.show-password': 'Mostrar senha',
                'Auth.form.register.news.label': 'Mantenha-me atualizado sobre os novos recursos e as próximas melhorias (ao fazer isso, você aceita os {terms} e a {policy}).',
                'Auth.form.register.subtitle': 'Suas credenciais são utilizadas somente para autenticar você ao painel de admin. Todos os dados serão salvos na sua própria base de dados.',
                'Auth.form.rememberMe.label': 'Lembre-se de mim',
                'Auth.form.username.label': 'Nome de usuário',
                'Auth.form.username.placeholder': 'Kai Doe',
                'Auth.link.forgot-password': 'Esqueceu sua senha?',
                'Auth.link.ready': 'Pronto para logar?',
                'Auth.link.signin': 'Entrar',
                'Auth.link.signin.account': 'Já tem uma conta?',
                'Auth.login.sso.divider': 'Ou entre com',
                'Auth.login.sso.loading': 'Carregando provedores...',
                'Auth.login.sso.subtitle': 'Entre na sua conta com SSO',
                'Auth.privacy-policy-agreement.policy': 'política de privacidade',
                'Auth.privacy-policy-agreement.terms': 'termos',
                'Auth.reset-password.title': 'Redefinir senha',

                // Content Manager e Builder
                'Content Manager': 'Gerenciador de conteúdo',
                'Content Type Builder': 'Criador de Tipos de Conteúdo',
                'Files Upload': 'Enviar arquivos',
                'HomePage.head.title': 'Pagina inicial',
                'HomePage.roadmap': 'Veja nosso roadmap',
                'HomePage.welcome.congrats': 'Parabéns!',
                'HomePage.welcome.congrats.content': 'Você está logado como o primeiro administrador. Para descobrir os recursos avançados fornecidos pelo Strapi,',
                'HomePage.welcome.congrats.content.bold': 'nós recomendados que você crie o seu primeiro Tipo de Conteúdo.',
                'Media Library': 'Biblioteca de Mídia',
                'New entry': 'Novo registro',

                // Roles e Permissions
                'Roles & Permissions': 'Funções e Permissões',
                'Roles.ListPage.notification.delete-all-not-allowed': 'Algumas funções não puderam ser removidos por estarem associadas a alguns usuários',
                'Roles.ListPage.notification.delete-not-allowed': 'A função não pode ser removida se ainda estiver associada a algum usuário',
                'Roles.RoleRow.select-all': 'Selecione {name} para ações em massa',
                'Roles.RoleRow.user-count': '{number, plural, =0 {#  user} um {#  user} outros {# users}}',
                'Roles.components.List.empty.withSearch': 'Não existe uma função correspondente à busca ({search})...',

                // Settings - General
                'Settings.PageTitle': 'Configurações - {name}',
                'Settings.error': 'Erro',
                'Settings.global': 'Configurações Globais',
                'Settings.permissions': 'Painel administrativo',

                // Settings - API Tokens
                'Settings.apiTokens.addFirstToken': 'Adicione sua primeira chave de API',
                'Settings.apiTokens.addNewToken': 'Adicionar nova chave de API',
                'Settings.apiTokens.create': 'Adicionar',
                'Settings.apiTokens.description': 'lista de chaves geradas para consumo da API',
                'Settings.apiTokens.emptyStateLayout': 'Você não tem nada aqui ainda...',
                'Settings.apiTokens.title': 'Chaves de API',
                'Settings.tokens.notification.copied': 'Chave copiada pra área de transferência.',
                'Settings.tokens.types.full-access': 'Acesso total',
                'Settings.tokens.types.read-only': 'Somente leitura',
                'Settings.tokens.copy.editMessage': 'Por motivos de segurança, você só poderá ver sua chave uma única vez.',
                'Settings.tokens.copy.editTitle': 'Essa chave não está mais acessível.',
                'Settings.tokens.copy.lastWarning': 'Certifique-se de copiar esta chave, pois não será possível vê-la novamente!',

                // Settings - Application
                'Settings.application.description': 'Informações globais do painel administrativo',
                'Settings.application.edition-title': 'edição atual',
                'Settings.application.get-help': 'Ajuda',
                'Settings.application.link-pricing': 'Ver todos os preços',
                'Settings.application.link-upgrade': 'Atualize seu painel administrativo',
                'Settings.application.node-version': 'versão do node',
                'Settings.application.strapi-version': 'versão do strapi',
                'Settings.application.strapiVersion': 'versão do strapi',
                'Settings.application.title': 'Visão geral',
                'Settings.application.customization': 'Customização',
                'Settings.application.customization.carousel.title': 'Logo',
                'Settings.application.customization.carousel.change-action': 'Alterar logotipo',
                'Settings.application.customization.carousel.reset-action': 'Redefinir logotipo',
                'Settings.application.customization.carousel-slide.label': 'Slide do logotipo',
                'Settings.application.customization.carousel-hint': 'Alterar o logotipo do painel de administração (Dimensão máxima: {dimension}x{dimension}, Tamanho máx.: {size}KB)',
                'Settings.application.customization.modal.cancel': 'Cancelar',
                'Settings.application.customization.modal.upload': 'Enviar',
                'Settings.application.customization.modal.tab.label': 'Como você deseja enviar seus arquivos?',
                'Settings.application.customization.modal.upload.from-computer': 'Do computador',
                'Settings.application.customization.modal.upload.file-validation': 'Dimensão máxima: {dimension}x{dimension}, Tamanho máximo: {size}KB',
                'Settings.application.customization.modal.upload.error-format': 'Formato incorreto (formatos aceitos: jpeg, jpg, png, svg).',
                'Settings.application.customization.modal.upload.error-size': 'O arquivo enviado é muito grande (dimensão máxima: {dimension}x{dimension}, tamanho máximo do arquivo: {size}KB)',
                'Settings.application.customization.modal.upload.error-network': 'Erro ao enviar o arquivo',
                'Settings.application.customization.modal.upload.cta.browse': 'Procurar arquivo',
                'Settings.application.customization.modal.upload.drag-drop': 'Arraste e solte o arquivo aqui ou',
                'Settings.application.customization.modal.upload.from-url': 'Da URL',
                'Settings.application.customization.modal.upload.from-url.input-label': 'URL',
                'Settings.application.customization.modal.upload.next': 'Próximo',
                'Settings.application.customization.modal.pending': 'Logotipo pendente',
                'Settings.application.customization.modal.pending.choose-another': 'Escolha outro logotipo',
                'Settings.application.customization.modal.pending.title': 'Logotipo pronto para ser enviado',
                'Settings.application.customization.modal.pending.subtitle': 'Gerencie o logotipo escolhido antes de fazer o upload',
                'Settings.application.customization.modal.pending.upload': 'Enviar',
                'Settings.application.customization.modal.pending.card-badge': 'imagem',

                // Settings - Permissions
                'Settings.permissions.category': 'Configurações de permissão da categoria {category}',
                'Settings.permissions.category.plugins': 'Configurações de permissão da extensão {category}',
                'Settings.permissions.conditions.anytime': 'A qualquer hora',
                'Settings.permissions.conditions.apply': 'Aplicar',
                'Settings.permissions.conditions.can': 'Pode',
                'Settings.permissions.conditions.conditions': 'Definir condições',
                'Settings.permissions.conditions.links': 'Links',
                'Settings.permissions.conditions.no-actions': 'Você precisa selecionar ações (criar, ler, editar, ...) antes de definir uma condição.',
                'Settings.permissions.conditions.none-selected': 'A qualquer hora',
                'Settings.permissions.conditions.or': 'OU',
                'Settings.permissions.conditions.when': 'Quando',
                'Settings.permissions.select-all-by-permission': 'Selecionar todas as permissões de {label}',
                'Settings.permissions.select-by-permission': 'Selecionar permissão de {label}',
                'Settings.permissions.users.create': 'Convidar novo usuário',
                'Settings.permissions.users.email': 'E-mail',
                'Settings.permissions.users.firstname': 'Primeiro nome',
                'Settings.permissions.users.lastname': 'Último nome',
                'Settings.permissions.users.form.sso': 'Conectar com SSO',
                'Settings.permissions.users.form.sso.description': 'Quando ativado, usuários podem se conectar com SSO',
                'Settings.permissions.users.listview.header.subtitle': 'Todos os usuários com acesso ao painel administrativo',
                'Settings.permissions.users.tabs.label': 'Permissões de Abas',

                // Settings - Profile
                'Settings.profile.form.notify.data.loaded': 'Os dados do seu pefil foram carregados',
                'Settings.profile.form.section.experience.clear.select': 'Limpar a linguagem da interface selecionada',
                'Settings.profile.form.section.experience.here': 'aqui',
                'Settings.profile.form.section.experience.interfaceLanguage': 'Linguagem da interface',
                'Settings.profile.form.section.experience.interfaceLanguage.hint': 'Somente sua interface será exibida com a linguagem selecionada.',
                'Settings.profile.form.section.experience.interfaceLanguageHelp': 'A nova linguagem seleciona só será exibida a você. Por favor, leia essa {documentation} para disponibilizar outras linguagens para sua equipe.',
                'Settings.profile.form.section.experience.mode.label': 'Modo de interface',
                'Settings.profile.form.section.experience.mode.hint': 'Selecione o modo de interface que você deseja usar',
                'Settings.profile.form.section.experience.mode.option-label': 'modo {name}',
                'Settings.profile.form.section.experience.title': 'Experiência',
                'Settings.profile.form.section.head.title': 'Perfil do usuário',
                'Settings.profile.form.section.profile.page.title': 'Página do perfil',

                // Settings - Roles
                'Settings.roles.create.description': 'Defina as permissões desse papel',
                'Settings.roles.create.title': 'Criar uma função',
                'Settings.roles.created': 'Função criada',
                'Settings.roles.edit.title': 'Editar uma função',
                'Settings.roles.form.button.users-with-role': '{number, plural, =0 {# usuários} um {# usuário} outros {# usuários}} com esse papel',
                'Settings.roles.form.created': 'Criado',
                'Settings.roles.form.description': 'Nome e descrição da função',
                'Settings.roles.form.permission.property-label': 'Permissões de {label}',
                'Settings.roles.form.permissions.attributesPermissions': 'Permissões de campos',
                'Settings.roles.form.permissions.create': 'Criar',
                'Settings.roles.form.permissions.delete': 'Remover',
                'Settings.roles.form.permissions.publish': 'Publicar',
                'Settings.roles.form.permissions.read': 'Ler',
                'Settings.roles.form.permissions.update': 'Editar',
                'Settings.roles.list.button.add': 'Adicionar novo papel',
                'Settings.roles.list.description': 'lista de papéis',
                'Settings.roles.title.singular': 'função',

                // Settings - SSO
                'Settings.sso.description': 'Configurações da funcionalidade de Single Sign-On.',
                'Settings.sso.form.defaultRole.description': 'Isso irá atribuir o novo usuário ao papel selecionado',
                'Settings.sso.form.defaultRole.description-not-allowed': 'Você precisa de permissão para ver os papéis administrativos',
                'Settings.sso.form.defaultRole.label': 'Função padrão',
                'Settings.sso.form.registration.description': 'Criar novo usuário ao logar por SSO e nenhuma conta existe previamente',
                'Settings.sso.form.registration.label': 'Inscrição automática',
                'Settings.sso.title': 'Single Sign-On',

                // Settings - Webhooks
                'Settings.webhooks.create': 'Criar um webhook',
                'Settings.webhooks.create.header': 'Adicionar um novo header',
                'Settings.webhooks.created': 'Webhook criado',
                'Settings.webhooks.event.publish-tooltip': 'Esse evento só está disponível para conteúdos com a funcionalidade de Rascunho/Publicado habilitada',
                'Settings.webhooks.events.create': 'Criar',
                'Settings.webhooks.events.update': 'Atualizar',
                'Settings.webhooks.form.events': 'Eventos',
                'Settings.webhooks.form.headers': 'Headers',
                'Settings.webhooks.form.url': 'Url',
                'Settings.webhooks.headers.remove': 'Remover header {number}',
                'Settings.webhooks.key': 'Chave',
                'Settings.webhooks.list.button.add': 'Adicionar novo webhook',
                'Settings.webhooks.list.description': 'Receba notificações de mudanças POST.',
                'Settings.webhooks.list.empty.description': 'Adicione o seu primeiro a essa lista.',
                'Settings.webhooks.list.empty.link': 'Veja nossa documentação',
                'Settings.webhooks.list.empty.title': 'Nenhum webhook adicionado ainda',
                'Settings.webhooks.list.th.actions': 'ações',
                'Settings.webhooks.list.th.status': 'estado',
                'Settings.webhooks.singular': 'webhook',
                'Settings.webhooks.title': 'Webhooks',
                'Settings.webhooks.to.delete': '{webhooksToDeleteLength, plural, one {# elemento} other {# elementos}} selecionado(s)',
                'Settings.webhooks.trigger': 'Disparo',
                'Settings.webhooks.trigger.cancel': 'Cancelar disparo',
                'Settings.webhooks.trigger.pending': 'Pendente…',
                'Settings.webhooks.trigger.save': 'Por favor salve para disparar',
                'Settings.webhooks.trigger.success': 'Sucesso!',
                'Settings.webhooks.trigger.success.label': 'Disparo realizado com sucesso',
                'Settings.webhooks.trigger.test': 'Disparo de teste',
                'Settings.webhooks.trigger.title': 'Salvar antes do Disparo',
                'Settings.webhooks.value': 'Valor',

                // Usecase
                'Usecase.back-end': 'Desenvolvedor Back-end',
                'Usecase.button.skip': 'Pular esta pergunta',
                'Usecase.content-creator': 'Criador de Conteúdo',
                'Usecase.front-end': 'Desenvolvedor Front-end',
                'Usecase.full-stack': 'Desenvolvedor Full-stack',
                'Usecase.input.work-type': 'Qual é o seu tipo de trabalho?',
                'Usecase.notification.success.project-created': 'Projeto criado com sucesso',
                'Usecase.other': 'Outro',
                'Usecase.title': 'Conte-nos um pouco mais sobre você',

                // Users
                'Users & Permissions': 'Usuários & Permissões',
                'Users.components.List.empty': 'Não há usuários...',
                'Users.components.List.empty.withFilters': 'Não há usuários correspondentes aos filtros...',
                'Users.components.List.empty.withSearch': 'Não há usuários correspondentes à busca ({search})...',

                // Marketplace
                'admin.pages.MarketPlacePage.head': 'Loja - Extensões',
                'admin.pages.MarketPlacePage.offline.title': 'Você está offline',
                'admin.pages.MarketPlacePage.offline.subtitle': 'Você precisa estar online para ver as extensões',
                'admin.pages.MarketPlacePage.plugins': 'Extensões',
                'admin.pages.MarketPlacePage.plugin.copy': 'Copiar comando de instalação',
                'admin.pages.MarketPlacePage.plugin.copy.success': 'Comando de instalação pronto para ser colado em seu terminal',
                'admin.pages.MarketPlacePage.plugin.info': 'Saber mais',
                'admin.pages.MarketPlacePage.plugin.info.label': 'Saiba mais sobre {pluginName}',
                'admin.pages.MarketPlacePage.plugin.info.text': 'Saber mais',
                'admin.pages.MarketPlacePage.plugin.installed': 'Instalado',
                'admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi': 'Criado por Strapi',
                'admin.pages.MarketPlacePage.plugin.tooltip.verified': 'Extensão verificada por Strapi',
                'admin.pages.MarketPlacePage.providers': 'Fornecedores',
                'admin.pages.MarketPlacePage.search.clear': 'Limpar busca',
                'admin.pages.MarketPlacePage.search.empty': 'Sem resultado para \"{target}\"',
                'admin.pages.MarketPlacePage.search.placeholder': 'Pesquisar',
                'admin.pages.MarketPlacePage.submit.plugin.link': 'Submeta sua extensão',
                'admin.pages.MarketPlacePage.submit.provider.link': 'Submeta provedor',
                'admin.pages.MarketPlacePage.subtitle': 'Faça mais com o Strapi',
                'admin.pages.MarketPlacePage.tab-group.label': 'Plugins e Provedores para Strapi',
                'admin.pages.MarketPlacePage.missingPlugin.title': 'Falta-lhe um plugin?',
                'admin.pages.MarketPlacePage.missingPlugin.description': 'Diga-nos qual extensão você está procurando e informaremos nossos desenvolvedores de extensões da comunidade caso eles estejam em busca de inspiração!',

                // App Components
                'app.component.CopyToClipboard.label': 'Copiar pra área de transferência',
                'app.component.search.label': 'Buscar por {target}',
                'app.component.table.duplicate': 'Duplicar {target}',
                'app.component.table.edit': 'Editar {target}',
                'app.component.table.select.one-entry': 'Selecionar {target}',
                'app.components.BlockLink.blog': 'Blog',
                'app.components.BlockLink.blog.content': 'Leia as últimas notícias do Strapi e seu ecossistema.',
                'app.components.BlockLink.code': 'Códigos de Exemplo',
                'app.components.BlockLink.code.content': 'Aprenda testando projetos desenvolvidos pela comunidade.',
                'app.components.BlockLink.documentation.content': 'Descubra os conceitos essenciais, guias e instruções.',
                'app.components.BlockLink.tutorial': 'Tutoriais',
                'app.components.BlockLink.tutorial.content': 'Siga o passo-a-passo para usar e customizar o Strapi.',
                'app.components.Button.cancel': 'Cancelar',
                'app.components.Button.confirm': 'Confirmar',
                'app.components.Button.reset': 'Resetar',
                'app.components.ComingSoonPage.comingSoon': 'Em breve',
                'app.components.ConfirmDialog.title': 'Confirmação',
                'app.components.DownloadInfo.download': 'Transferência em andamento...',
                'app.components.DownloadInfo.text': 'Isto poderá levar alguns minutos. Obrigado pela sua paciência',
                'app.components.EmptyAttributes.title': 'Ainda não existem campos',

                // Adicione estas chaves ao seu arquivo de configuração PT-BR

                'Settings.apiTokens.ListView.headers.createdAt': 'Criado em',
                'Settings.apiTokens.ListView.headers.description': 'Descrição',
                'Settings.apiTokens.ListView.headers.lastUsedAt': 'Último uso',
                'Settings.apiTokens.ListView.headers.name': 'Nome',
                'Settings.apiTokens.ListView.headers.type': 'Tipo de token',
                'Settings.apiTokens.createPage.BoundRoute.title': 'Rota vinculada a',
                'Settings.apiTokens.createPage.permissions.description': 'Apenas ações vinculadas por uma rota são listadas abaixo.',
                'Settings.apiTokens.createPage.permissions.header.hint': 'Selecione as ações da aplicação ou as ações do plugin e clique no ícone de engrenagem para exibir a rota vinculada',
                'Settings.apiTokens.createPage.permissions.header.title': 'Configurações avançadas',
                'Settings.apiTokens.createPage.permissions.title': 'Permissões',
                'Settings.apiTokens.createPage.title': 'Criar Token de API',
                'Settings.apiTokens.regenerate': 'Regenerar',
                'Settings.apiTokens.lastHour': 'última hora',
                'Settings.application.customization.auth-logo.carousel-hint': 'Substitua o logotipo nas páginas de autenticação',
                'Settings.application.customization.carousel.auth-logo.title': 'Logotipo de autenticação',
                'Settings.application.customization.carousel.menu-logo.title': 'Logotipo do menu',
                'Settings.application.customization.menu-logo.carousel-hint': 'Substitua o logotipo na navegação principal',
                'Settings.application.customization.size-details': 'Dimensão máx.: {dimension}×{dimension}, Tamanho máx. do arquivo: {size}KB',
                'Settings.application.ee-or-ce': '{communityEdition, select, true {Edição Comunitária} other {Edição Empresarial}}',
                'Settings.application.ee.admin-seats.add-seats': 'Gerenciar lugares',
                'Settings.application.ee.admin-seats.support': 'Contate vendas',
                'Settings.application.ee.admin-seats.at-limit-tooltip': 'Limite atingido: adicione lugares para convidar mais usuários',
                'Settings.application.ee.admin-seats.count': '<text>{enforcementUserCount}</text>/{permittedSeats}',
                'Settings.permissions.auditLogs.admin.auth.success': 'Login do administrador',
                'Settings.permissions.auditLogs.admin.logout': 'Logout do administrador',
                'Settings.permissions.auditLogs.component.create': 'Criar componente',
                'Settings.permissions.auditLogs.component.delete': 'Deletar componente',
                'Settings.permissions.auditLogs.component.update': 'Atualizar componente',
                'Settings.permissions.auditLogs.content-type.create': 'Criar tipo de conteúdo',
                'Settings.permissions.auditLogs.content-type.delete': 'Deletar tipo de conteúdo',
                'Settings.permissions.auditLogs.content-type.update': 'Atualizar tipo de conteúdo',
                'Settings.permissions.auditLogs.details': 'Detalhes do Log',
                'Settings.permissions.auditLogs.entry.create': 'Criar entrada{model, select, undefined {} other { ({model})}}',
                'Settings.permissions.auditLogs.entry.delete': 'Deletar entrada{model, select, undefined {} other { ({model})}}',
                'Settings.permissions.auditLogs.entry.publish': 'Publicar entrada {model, select, undefined {} other {({model})}}',
                'Settings.permissions.auditLogs.entry.unpublish': 'Despublicar entrada{model, select, undefined {} other { ({model})}}',
                'Settings.permissions.auditLogs.entry.update': 'Atualizar entrada{model, select, undefined {} other { ({model})}}',
                'Settings.permissions.auditLogs.filters.combobox.aria-label': 'Pesquise e selecione uma opção para filtrar',
                'Settings.permissions.auditLogs.listview.header.subtitle': 'Logs de todas as atividades que aconteceram no seu ambiente',
                'Settings.permissions.auditLogs.not-available': 'Logs de Auditoria está disponível apenas como parte de um plano pago. Atualize para obter uma exibição pesquisável e filtrável de todas as atividades.',
                'Settings.permissions.auditLogs.media.create': 'Criar mídia',
                'Settings.permissions.auditLogs.media.delete': 'Deletar mídia',
                'Settings.permissions.auditLogs.media.update': 'Atualizar mídia',
                'Settings.permissions.auditLogs.permission.create': 'Criar permissão',
                'Settings.permissions.auditLogs.permission.delete': 'Deletar permissão',
                'Settings.permissions.auditLogs.permission.update': 'Atualizar permissão',
                'Settings.permissions.auditLogs.role.create': 'Criar função',
                'Settings.permissions.auditLogs.role.delete': 'Deletar função',
                'Settings.permissions.auditLogs.role.update': 'Atualizar função',
                'Settings.permissions.auditLogs.userId': 'ID do Usuário',
                'Settings.permissions.conditions.define-conditions': 'Definir condições',
                'Settings.permissions.users.active': 'Ativo',
                'Settings.permissions.users.sso.provider.error': 'Ocorreu um erro ao solicitar as configurações de SSO',
                'Settings.permissions.users.inactive': 'Inativo',
                'Settings.permissions.users.roles': 'Funções',
                'Settings.permissions.users.strapi-author': 'Autor',
                'Settings.permissions.users.strapi-editor': 'Editor',
                'Settings.permissions.users.strapi-super-admin': 'Super Admin',
                'Settings.permissions.users.user-status': 'Status do usuário',
                'Settings.permissions.users.username': 'Nome de usuário',
                'Settings.profile.form.section.experience.mode.option-system-label': 'Usar configurações do sistema',
                'Settings.sso.form.localAuthenticationLock.label': 'Bloqueio de autenticação local',
                'Settings.sso.form.localAuthenticationLock.description': 'Selecione as funções para as quais deseja desabilitar a autenticação local',
                'Settings.sso.not-available': 'SSO está disponível apenas como parte de um plano pago. Atualize para configurar métodos adicionais de login e cadastro no seu painel administrativo.',
                'Settings.content-history.title': 'Histórico de Conteúdo',
                'Settings.content-history.description': 'Obtenha mais controle sobre cada etapa do ciclo de vida do seu conteúdo.',
                'Settings.content-history.not-available': 'Histórico de Conteúdo está disponível apenas como parte de um plano pago. Atualize para obter controle total sobre o ciclo de vida do seu conteúdo.',
                'Settings.tokens.Button.cancel': 'Cancelar',
                'Settings.tokens.Button.regenerate': 'Regenerar',
                'Settings.tokens.ListView.headers.createdAt': 'Criado em',
                'Settings.tokens.ListView.headers.description': 'Descrição',
                'Settings.tokens.ListView.headers.lastUsedAt': 'Último uso',
                'Settings.tokens.ListView.headers.name': 'Nome',
                'Settings.tokens.copy.title': 'Token',
                'Settings.tokens.duration.expiration-date': 'Data de expiração',
                'Settings.tokens.form.description': 'Descrição',
                'Settings.tokens.form.name': 'Nome',
                'Settings.tokens.form.type': 'Tipo de token',
                'Settings.tokens.types.custom': 'Personalizado',
                'Settings.transferTokens.ListView.headers.type': 'Tipo de token',
                'Settings.transferTokens.addFirstToken': 'Adicione seu primeiro Token de Transferência',
                'Settings.transferTokens.addNewToken': 'Adicionar novo Token de Transferência',
                'Settings.transferTokens.create': 'Criar novo Token de Transferência',
                'Settings.transferTokens.createPage.title': 'Criar Token de Transferência',
                'Settings.transferTokens.description': 'Lista de tokens de transferência gerados',
                'Settings.transferTokens.emptyStateLayout': 'Você não tem nada aqui ainda...',
                'Settings.transferTokens.title': 'Tokens de Transferência',
                'Settings.webhooks.event.select': 'Selecionar evento',
                'Settings.webhooks.events.isLoading': 'Carregando eventos',
                'Settings.webhooks.events.delete': 'Deletar webhook',
                'Settings.webhooks.list.loading.success': 'Webhooks foram carregados',
                'Settings.webhooks.validation.name.required': 'Nome é obrigatório',
                'Settings.webhooks.validation.name.regex': 'O nome deve começar com uma letra e conter apenas letras, números, espaços e underscores',
                'Settings.webhooks.validation.url.required': 'URL é obrigatória',
                'Settings.webhooks.validation.url.regex': 'O valor deve ser uma URL válida',
                'Settings.webhooks.validation.key': 'Chave é obrigatória',
                'Settings.webhooks.validation.value': 'Valor é obrigatório',
                'Settings.page.PurchaseAudit-logs.description': 'Acompanhe e revise mudanças com sua equipe',
                'Settings.page.PurchaseAudit-logs.perks1': 'Acompanhe mudanças facilmente',
                'Settings.page.PurchaseAudit-logs.perks2': 'Revise mudanças com facilidade',
                'Settings.page.PurchaseAudit-logs.perks3': 'Mantenha segurança e conformidade',
                'Settings.page.PurchaseContent-history.description': 'Reverta mudanças de conteúdo instantaneamente',
                'Settings.page.PurchaseContent-history.perks1': 'Navegue pelo histórico do seu conteúdo',
                'Settings.page.PurchaseContent-history.perks2': 'Reverta mudanças em um clique',
                'Settings.page.PurchaseContent-history.perks3': 'Acompanhe mudanças em locales',
                'Settings.page.PurchaseSSO.description': 'Simplifique a autenticação para sua equipe',
                'Settings.page.PurchaseSSO.perks1': 'Autenticação unificada',
                'Settings.page.PurchaseSSO.perks2': 'Segurança aprimorada',
                'Settings.page.PurchaseSSO.perks3': 'Suporte para webhooks',
                'Settings.page.purchase.upgrade.cta': 'Atualizar',
                'Settings.page.purchase.learn-more.cta': 'Saiba mais',
                'admin.pages.MarketPlacePage.sort.label': 'Ordenar por',
                'admin.pages.MarketPlacePage.filters.categories': 'Categorias',
                'admin.pages.MarketPlacePage.filters.categoriesSelected': '{count, plural, =0 {Nenhuma categoria} one {# categoria} other {# categorias}} selecionada(s)',
                'admin.pages.MarketPlacePage.filters.collections': 'Coleções',
                'admin.pages.MarketPlacePage.filters.collectionsSelected': '{count, plural, =0 {Nenhuma coleção} one {# coleção} other {# coleções}} selecionada(s)',
                'admin.pages.MarketPlacePage.plugin.downloads': 'Este plugin tem {downloadsCount} downloads semanais',
                'admin.pages.MarketPlacePage.plugin.githubStars': 'Este plugin recebeu {starsCount} estrelas no GitHub',
                'admin.pages.MarketPlacePage.plugin.version': 'Atualize sua versão do Strapi: \"{strapiAppVersion}\" para: \"{versionRange}\"',
                'admin.pages.MarketPlacePage.plugin.version.null': 'Não é possível verificar compatibilidade com sua versão do Strapi: \"{strapiAppVersion}\"',
                'admin.pages.MarketPlacePage.provider.downloads': 'Este provedor tem {downloadsCount} downloads semanais',
                'admin.pages.MarketPlacePage.provider.githubStars': 'Este provedor recebeu {starsCount} estrelas no GitHub',
                'admin.pages.MarketPlacePage.sort.alphabetical': 'Ordem alfabética',
                'admin.pages.MarketPlacePage.sort.alphabetical.selected': 'Ordenar por ordem alfabética',
                'admin.pages.MarketPlacePage.sort.githubStars': 'Número de estrelas do GitHub',
                'admin.pages.MarketPlacePage.sort.githubStars.selected': 'Ordenar por estrelas do GitHub',
                'admin.pages.MarketPlacePage.sort.newest': 'Mais novo',
                'admin.pages.MarketPlacePage.sort.newest.selected': 'Ordenar por mais novo',
                'admin.pages.MarketPlacePage.sort.npmDownloads': 'Número de downloads',
                'admin.pages.MarketPlacePage.sort.npmDownloads.selected': 'Ordenar por downloads npm',
                'app.component.table.read': 'Ler {target}',
                'app.component.table.view': '{target} detalhes',
                'app.components.BlockLink.cloud': 'Strapi Cloud',
                'app.components.BlockLink.cloud.content': 'Hospedagem em nuvem totalmente gerenciada para seu projeto Strapi.',
                'app.components.ToggleCheckbox.enabled-label': 'Habilitado',
                'app.components.ToggleCheckbox.disabled-label': 'Desabilitado',
                'app.components.FreeTrialEndedModal.button.downgrade': 'Desatualizar para Comunidade',
                'app.components.FreeTrialEndedModal.button.upgrade': 'Manter no plano Growth',
                'app.components.FreeTrialEndedModal.description': 'Seu acesso aos recursos do plano Growth, como Histórico de Conteúdo, Releases e Single Sign-On (SSO) expirou.',
                'app.components.FreeTrialEndedModal.notice.item1': 'Desatualizar removerá o acesso aos recursos acima.',
                'app.components.FreeTrialEndedModal.notice.item2': 'O histórico de versão do documento será deletado.',
                'app.components.FreeTrialEndedModal.notice.item3': 'Todos os releases serão apagados.',
                'app.components.FreeTrialEndedModal.notice.item4': 'Se desatualizar, certifique-se de definir uma senha de admin raiz para manter o acesso ao painel administrativo.',
                'app.components.FreeTrialEndedModal.notice.title': 'Importante saber:',
                'app.components.FreeTrialEndedModal.title': 'Seu período de teste terminou',
                'app.components.FreeTrialWelcomeModal.button': 'Começar a explorar',
                'app.components.FreeTrialWelcomeModal.description1': 'Pelos próximos 30 dias, você terá acesso total a recursos avançados como Histórico de Conteúdo, Releases e Single Sign-On (SSO) – tudo que você precisa para explorar o poder do Strapi CMS.',
                'app.components.FreeTrialWelcomeModal.description2': 'Use este tempo para construir, personalizar e testar seus fluxos de trabalho de conteúdo com total flexibilidade!',
                'app.components.FreeTrialWelcomeModal.title': 'Ficamos felizes em tê-lo(a) a bordo',
                'app.components.Onboarding.link.build-content': 'Construa uma arquitetura de conteúdo',
                'app.components.Onboarding.link.manage-content': 'Adicionar e gerenciar conteúdo',
                'app.components.Onboarding.link.manage-media': 'Gerenciar mídia',
                'app.components.Onboarding.link.more-videos': 'Assistir mais vídeos',
                'app.components.UpsellBanner.button': 'Atualizar agora',
                'app.components.UpsellBanner.intro': 'Acesso aos recursos do plano Growth: ',
                'app.components.UpsellBanner.text': 'Como parte de seu teste, você pode explorar ferramentas premium como Histórico de Conteúdo, Releases e Single Sign-On (SSO).',
                'app.components.ToggleCheckbox.off-label': 'Falso',
                'app.components.ToggleCheckbox.on-label': 'Verdadeiro',
                'app.utils.delete': 'Deletar',
                'app.utils.refresh': 'Atualizar',
                'app.utils.published': 'Publicado',
                'app.utils.ready-to-publish': 'Pronto para publicar',
                'app.utils.already-published': 'Já publicado',
                'app.utils.ready-to-publish-changes': 'Pronto para publicar mudanças',
                'app.utils.ready-to-unpublish-changes': 'Pronto para despublicar',
                'app.confirm.body': 'Tem certeza?',
                'noPreview': 'Nenhuma visualização disponível',
                'selectButtonTitle': 'Selecionar',
                'components.Input.error.contain.maxBytes': 'Senha deve ter menos de 73 bytes',
                'components.Input.error.validation.combobox.invalid': 'O valor fornecido não é válido',
                'components.Input.error.validation.string': 'Isto não é uma string válida',
                'components.Input.error.validation.email.withField': '{field} é um email inválido',
                'components.Input.error.validation.json.withField': '{field} não corresponde ao formato JSON',
                'components.Input.error.validation.lowercase.withField': '{field} deve ser uma string em minúsculas',
                'components.Input.error.validation.max.withField': '{field} é muito alto.',
                'components.Input.error.validation.maxLength.withField': '{field} é muito longo.',
                'components.Input.error.validation.min.withField': '{field} é muito baixo.',
                'components.Input.error.validation.minLength.withField': '{field} é muito curto.',
                'components.Input.error.validation.minSupMax.withField': '{field} não pode ser superior',
                'components.Input.error.validation.regex.withField': '{field} não corresponde ao regex.',
                'components.Input.error.validation.required.withField': '{field} é obrigatório.',
                'components.Input.error.validation.unique.withField': '{field} já está em uso.',
                'components.OverlayBlocker.description.serverError': 'O servidor deve ter sido reiniciado. Verifique seus registros no terminal.',
                'components.OverlayBlocker.title.serverError': 'A reinicialização está demorando mais que o esperado',
                'components.ViewSettings.tooltip': 'Ver configurações',
                'components.Blocks.modifiers.bold': 'Negrito',
                'components.Blocks.modifiers.italic': 'Itálico',
                'components.Blocks.modifiers.underline': 'Sublinhado',
                'components.Blocks.modifiers.strikethrough': 'Tachado',
                'components.Blocks.modifiers.code': 'Código em linha',
                'components.Blocks.link': 'Link',
                'components.Blocks.expand': 'Expandir',
                'components.Blocks.collapse': 'Recolher',
                'components.Blocks.popover.text': 'Texto',
                'components.Blocks.popover.text.placeholder': 'Digite o texto do link',
                'components.Blocks.popover.link': 'Link',
                'components.Blocks.popover.link.placeholder': 'Cole o link',
                'components.Blocks.popover.link.rel': 'Rel (opcional)',
                'components.Blocks.popover.link.rel.placeholder': 'noopener, nofollow, noreferrer',
                'components.Blocks.popover.link.target': 'Alvo (opcional)',
                'components.Blocks.popover.link.target.placeholder': '_blank, _self, _parent, _top',
                'components.Blocks.popover.link.error': 'Por favor, digite um link válido',
                'components.Blocks.popover.remove': 'Remover',
                'components.Blocks.popover.edit': 'Editar',
                'components.Blocks.blocks.selectBlock': 'Selecione um bloco',
                'components.Blocks.blocks.text': 'Texto',
                'components.Blocks.blocks.heading1': 'Cabeçalho 1',
                'components.Blocks.blocks.heading2': 'Cabeçalho 2',
                'components.Blocks.blocks.heading3': 'Cabeçalho 3',
                'components.Blocks.blocks.heading4': 'Cabeçalho 4',
                'components.Blocks.blocks.heading5': 'Cabeçalho 5',
                'components.Blocks.blocks.heading6': 'Cabeçalho 6',
                'components.Blocks.blocks.code': 'Bloco de código',
                'components.Blocks.blocks.quote': 'Citação',
                'components.Blocks.blocks.image': 'Imagem',
                'components.Blocks.blocks.unorderedList': 'Lista com marcadores',
                'components.Blocks.blocks.orderedList': 'Lista numerada',
                'components.Blocks.blocks.code.languageLabel': 'Selecione uma linguagem',
                'components.Blocks.dnd.instruction': 'Para reordenar blocos, pressione Command ou Control junto com Shift e as teclas de seta para Cima ou Baixo',
                'components.Blocks.dnd.reorder': '{item}, movido. Nova posição no editor: {position}.',
                'components.Wysiwyg.collapse': 'Recolher',
                'components.Wysiwyg.blocks.code': 'Código',
                'components.Wysiwyg.selectOptions.H1': 'Cabeçalho 1',
                'components.Wysiwyg.selectOptions.H2': 'Cabeçalho 2',
                'components.Wysiwyg.selectOptions.H3': 'Cabeçalho 3',
                'components.Wysiwyg.selectOptions.H4': 'Cabeçalho 4',
                'components.Wysiwyg.selectOptions.H5': 'Cabeçalho 5',
                'components.Wysiwyg.selectOptions.H6': 'Cabeçalho 6',
                'components.Wysiwyg.selectOptions.title': 'Cabeçalhos',
                'components.WysiwygBottomControls.charactersIndicators': 'caracteres',
                'components.WysiwygBottomControls.fullscreen': 'Expandir',
                'components.WysiwygBottomControls.uploadFiles': 'Arraste e solte arquivos, cole da área de transferência ou {browse}.',
                'components.WysiwygBottomControls.uploadFiles.browse': 'selecione-os',
                'components.pagination.go-to': 'Ir para página {page}',
                'components.pagination.go-to-next': 'Ir para próxima página',
                'components.pagination.go-to-previous': 'Ir para página anterior',
                'components.pagination.remaining-links': 'E {number} outros links',
                'components.popUpWarning.message': 'Tem certeza que deseja deletar isto?',
                'components.premiumFeature.title': 'Recurso Premium',
                'global.close': 'Fechar',
                'global.home': 'Início',
                'global.error': 'Algo deu errado',
                'global.last-change.redo': 'Refazer última mudança',
                'global.last-change.undo': 'Desfazer última mudança',
                'global.last-changes.discard': 'Descartar últimas mudanças',
                'global.marketplace': 'Marketplace',
                'global.more': 'Mais',
                'global.new': 'Novo',
                'global.profile.settings': 'Configurações de perfil',
                'global.fullname': '{firstname} {lastname}',
                'global.learn-more': 'Saiba mais',
                'notification.error.invalid.configuration': 'Você tem uma configuração inválida, verifique seu log do servidor para mais informações.',
                'notification.error.tokennamenotunique': 'Nome já atribuído a outro token',
                'notification.success.apitokencreated': 'Token de API criado com sucesso',
                'notification.success.apitokenedited': 'Token de API editado com sucesso',
                'notification.success.transfertokencreated': 'Token de Transferência criado com sucesso',
                'notification.success.transfertokenedited': 'Token de Transferência editado com sucesso',
                'notification.ee.warning.at-seat-limit.title': '{licenseLimitStatus, select, OVER_LIMIT {Acima do} AT_LIMIT {No}} limite de lugares ({currentUserCount}/{permittedSeats})',
                'notification.ee.warning.over-.message': 'Adicione lugares para {licenseLimitStatus, select, OVER_LIMIT {convidar} AT_LIMIT {reabilitar}} Usuários. Se você já fez isso mas ainda não está refletido no Strapi, certifique-se de reiniciar seu app.',
                'tours.contentTypeBuilder.Introduction.title': 'Bem-vindo ao Criador de Tipos de Conteúdo!',
                'tours.contentTypeBuilder.Introduction.content': 'Aqui você cria e gerencia a estrutura do seu app com tipos de coleção, tipos únicos e componentes reutilizáveis. Vamos lá!',
                'tours.contentTypeBuilder.AIChat.title': 'Hora de começar!',
                'tours.contentTypeBuilder.AIChat.content': `<p>Se você tiver dúvidas sobre o Criador de Tipos de Conteúdo ou Strapi, pergunte aqui.</p><p>O Strapi AI pode gerar esquemas adaptados às suas necessidades. Peça exatamente o que deseja, por exemplo:<ul><li>Seletor de data</li><li>Campos de email e senha</li><li>Mídia de qualquer tipo</li><li>UIDs</li></ul></p><p>Não seja tímido, experimente!</p>`,
                'tours.contentTypeBuilder.CollectionTypes.title': 'Tipos de Coleção',
                'tours.contentTypeBuilder.CollectionTypes.content': 'Estes são os ideais para gerenciar múltiplas entradas — pense em postagens de blog ou produtos.',
                'tours.contentTypeBuilder.SingleTypes.title': 'Tipos Únicos',
                'tours.contentTypeBuilder.SingleTypes.content': 'Perfeito para entradas únicas como sua página inicial ou configurações do site.',
                'tours.contentTypeBuilder.Components.title': 'Componentes',
                'tours.contentTypeBuilder.Components.content': 'Construa uma vez, reutilize em qualquer lugar. Use componentes para coisas como botões, cards ou controles deslizantes.',
                'tours.contentTypeBuilder.YourTurn.title': 'Sua vez — Construa algo!',
                'tours.contentTypeBuilder.YourTurn.content': 'Vá em frente e crie um tipo de coleção ou tipo único. Clique no botão "+", escolha um nome, clique em "Continuar" e guiaremos você a partir daí.',
                'tours.contentTypeBuilder.AddFields.title': 'Adicione um campo para dar vida a ele',
                'tours.contentTypeBuilder.AddFields.content': 'Comece adicionando seu primeiro campo — como um nome, imagem ou relação. Seu tipo de conteúdo precisa de uma forma antes de poder conter conteúdo.',
                'tours.contentTypeBuilder.Save.title': 'Não saia sem salvar!',
                'tours.contentTypeBuilder.Save.content': 'Clique no botão "Salvar" para confirmar seu tipo de conteúdo e evitar perder seu trabalho. Quase pronto!',
                'tours.contentTypeBuilder.Finish.title': 'Primeiro Passo: Concluído! 🎉',
                'tours.contentTypeBuilder.Finish.content': 'Você construiu seu primeiro tipo de conteúdo! Agora vá para o Gerenciador de Conteúdo para começar a adicionar entradas!',
                'tours.apiTokens.Introduction.title': 'Por último, mas não menos importante, tokens de API',
                'tours.apiTokens.Introduction.content': 'Controle o acesso à API com permissões altamente personalizáveis.',
                'tours.apiTokens.ManageAPIToken.title': 'Gerencie um token de API',
                'tours.apiTokens.ManageAPIToken.content': 'Clique no ícone "Lápis" para visualizar e atualizar um token de API existente.',
                'tours.apiTokens.ViewAPIToken.title': 'Ver token de API',
                'tours.apiTokens.ViewAPIToken.content': 'Clique no botão',

                // Audit Logs - User (faltava)
                'Settings.permissions.auditLogs.user.create': 'Criar usuário',
                'Settings.permissions.auditLogs.user.delete': 'Deletar usuário',
                'Settings.permissions.auditLogs.user.fullname': '{firstname} {lastname}',
                'Settings.permissions.auditLogs.user.update': 'Atualizar usuário',


                // App Components - Guided Tour (muito faltava)
                'app.components.GuidedTour.CM.create.content': '<p>Crie e gerencie todo o conteúdo aqui no Gerenciador de Conteúdos.</p><p>Ex: Levando ainda mais o exemplo do site do Blog, pode-se escrever um artigo, salvá-lo e publicá-lo como quiser.</p><p>💡 Dica rápida - Não se esqueça de clicar em publicar no conteúdo que você criar.</p>',
                'app.components.GuidedTour.CM.create.title': '⚡️ Crie seu primeiro conteúdo',
                'app.components.GuidedTour.CM.success.content': '<p>Incrível, falta um último passo!</p><b>🚀 Ver conteúdo em ação</b>',
                'app.components.GuidedTour.CM.success.cta.title': 'Teste a API',
                'app.components.GuidedTour.CM.success.title': 'Passo 2: Concluído ✅',
                'app.components.GuidedTour.CTB.create.content': '<p>Os tipos de coleção ajudam a gerenciar várias entradas, os tipos únicos são adequados para gerenciar apenas uma entrada.</p> <p>Ex: Para um site de blog, os artigos seriam um tipo de coleção, enquanto uma página inicial seria um tipo único.</p>',
                'app.components.GuidedTour.CTB.create.cta.title': 'Criar um Tipo de Coleção',
                'app.components.GuidedTour.CTB.create.title': '🧠 Criar um primeiro tipo de coleção',
                'app.components.GuidedTour.CTB.success.content': '<p>Bom trabalho!</p><b>⚡️ O que você gostaria de compartilhar com o mundo?</b>',
                'app.components.GuidedTour.CTB.success.title': 'Passo 1: Concluído ✅',
                'app.components.GuidedTour.apiTokens.create.content': '<p>Gere um token de autenticação aqui e recupere o conteúdo que você acabou de criar.</p>',
                'app.components.GuidedTour.apiTokens.create.cta.title': 'Gerar um token de API',
                'app.components.GuidedTour.apiTokens.create.title': '🚀 Visualizar conteúdo em ação',
                'app.components.GuidedTour.apiTokens.success.content': '<p>Visualize o conteúdo em ação fazendo uma solicitação HTTP:</p><ul><li><p>Para esta URL: <light>https://\'<\'YOUR_DOMAIN\'>\'/api/\'<\'YOUR_CT\'>\' </light></p></li><li><p>Com o cabeçalho: <light>Authorization: bearer \'<\'YOUR_API_TOKEN\' >\'</light></p></li></ul><p>Para mais formas de interagir com o conteúdo, consulte a <documentationLink>documentação</documentationLink>.</p>',
                'app.components.GuidedTour.apiTokens.success.cta.title': 'Voltar para a página inicial',
                'app.components.GuidedTour.apiTokens.success.title': 'Passo 3: Concluído ✅',
                'app.components.GuidedTour.home.CTB.cta.title': 'Ir para o Criador de tipos de conteúdo',

                // HomePage - Welcome (faltava)
                'app.components.HomePage.button.blog': 'Veja mais no blog',
                'app.components.HomePage.community': 'Nossa comunidade na web',
                'app.components.HomePage.community.content': 'Converse com membros da equipe, colaboradores e desenvolvedores em diversos canais.',
                'app.components.HomePage.create': 'Crie seu primeiro Tipo de Conteúdo',
                'app.components.HomePage.roadmap': 'Veja nosso roadmap',
                'app.components.HomePage.welcome': 'Bem-vindo(a) a bordo 👋',
                'app.components.HomePage.welcome.again': 'Bem-vindo(a) 👋',
                'app.components.HomePage.welcomeBlock.content': 'Estamos muito felizes em tê-lo(a) como um membro da nossa comunidade. Estamos sempre querendo saber sua opinião, então fique a vontade em nos enviar uma mensagem em privado no',
                'app.components.HomePage.welcomeBlock.content.again': 'Desejamos que você esteja progredindo em seu projeto... Fique por dentro das últimas novidades sobre o Strapi. Estamos sempre dando o nosso melhor para melhorar o produto sempre baseando-se em sua opinião.',
                'app.components.HomePage.welcomeBlock.content.issues': 'problemas.',
                'app.components.HomePage.welcomeBlock.content.raise': 'ou aponte',

                // App Components - LeftMenu Trial (faltava)
                'app.components.LeftMenu.trialCountdown.endedAt': 'Seu período de teste terminou em {date}.',
                'app.components.LeftMenu.trialCountdown.endsAt': 'Seu período de teste termina em {date}.',
                // Widgets (faltava)
                'widget.key-statistics.title': 'Estatísticas do projeto',
                'widget.key-statistics.list.admins': 'Administradores',
                'widget.key-statistics.list.apiTokens': 'Tokens de API',
                'widget.key-statistics.list.assets': 'Ativos',
                'widget.key-statistics.list.components': 'Componentes',
                'widget.key-statistics.list.contentTypes': 'Tipos de Conteúdo',
                'widget.key-statistics.list.entries': 'Entradas',
                'widget.key-statistics.list.locales': 'Locales',
                'widget.key-statistics.list.webhooks': 'Webhooks',
                'widget.last-activity.link': 'Abrir Logs de Auditoria',
                'widget.last-activity.no-activity': 'Sem atividade',
                'widget.last-activity.title': 'Última atividade',
                'widget.profile.title': 'Perfil',

                // HomePage - Add Widget (faltava)
                'HomePage.addWidget.title': 'Adicionar Widget',
                'HomePage.addWidget.noWidgetsAvailable': 'Nenhum widget disponível para adicionar',
                'HomePage.addWidget.button': 'Adicionar Widget',
                'HomePage.widget.delete': 'Deletar',
                'HomePage.widget.drag': 'Arrastar para mover',
                // Components - Wysiwyg (faltava)
                'components.Wysiwyg.ToggleMode.markdown-mode': 'Modo de edição',
                'components.Wysiwyg.ToggleMode.preview-mode': 'Modo de visualização',

                // Tours - Complete (faltava muita coisa)
                'tours.contentManager.Introduction.title': 'Gerenciador de conteúdo',
                'tours.contentManager.Introduction.content': 'Crie e gerencie conteúdo a partir de seus tipos de coleção e tipos únicos.',
                'tours.contentManager.CreateNewEntry.title': 'Criar nova entrada',
                'tours.contentManager.CreateNewEntry.content': 'Clique no botão "Criar nova entrada" para criar e publicar uma nova entrada para este tipo de coleção.',
                'tours.contentManager.Fields.title': 'Campos',
                'tours.contentManager.Fields.content': 'Primeiro, preencha os campos que você criou no Construtor de Tipos de Conteúdo.',
                'tours.contentManager.Publish.title': 'Publicar',
                'tours.contentManager.Publish.content': 'Em seguida, clique no botão "Publicar" para disponibilizar seu conteúdo através da API de conteúdo.',
                'tours.contentManager.FinalStep.title': 'Hora de configurar tokens de API!',
                'tours.contentManager.FinalStep.content': 'Agora que você criou e publicou uma entrada, vamos configurar um token de API para gerenciar o acesso ao seu conteúdo.',
                'tours.stepCount': 'Etapa {currentStep} de {tourLength}',
                'tours.skip': 'Pular',
                'tours.next': 'Próximo',
                'tours.gotIt': 'Entendi',
                'tours.overview.title': 'Descubra sua aplicação!',
                'tours.overview.subtitle': 'Siga o tour guiado para aproveitar o Strapi ao máximo.',
                'tours.overview.close': 'Fechar tour guiado',
                'tours.overview.tasks': 'Suas tarefas',
                'tours.overview.contentTypeBuilder.label': 'Crie seu esquema',
                'tours.overview.contentManager.label': 'Crie e publique conteúdo',
                'tours.overview.apiTokens.label': 'Copie um token de API',
                'tours.overview.strapiCloud.label': 'Implante sua aplicação no Strapi Cloud',
                'tours.overview.strapiCloud.link': 'Ler documentação',
                'tours.overview.tour.link': 'Começar',
                'tours.overview.tour.done': 'Pronto',
                'tours.overview.close.description': 'Você tem certeza que deseja fechar o tour guiado?',
                'tours.profile.title': 'Tour guiado',
                'tours.profile.description': 'Você pode redefinir o tour guiado a qualquer momento.',
                'tours.profile.reset': 'Redefinir tour guiado',
                'tours.profile.notification.success.reset': 'Tour guiado redefinido',
                'tours.overview.completed': '{completed}% concluído',
                'tours.apiTokens.CopyAPIToken.title': 'Copie seu token de API',
                'tours.apiTokens.CopyAPIToken.content': 'Clique no botão "Copiar" para salvar seu token de API, você precisará dele para fazer solicitações à sua aplicação. {spacer} Ainda tem dúvidas? Saiba mais sobre <a>tokens de API</a>.',
                'tours.apiTokens.FinalStep.title': 'Parabéns, é hora de implantar sua aplicação!',
                'tours.apiTokens.FinalStep.content': 'Você tem tudo que precisa para implantar sua aplicação e compartilhar conteúdo com o mundo.',

            }
        },
        // AQUI MUDAMOS AS CORES
        theme: {
            // Tema Claro (Light)
            light: {
                colors: {
                    // Cor Principal (Botões, Links ativos) - Usando seu Brand #BC8E38
                    primary100: '#fcf2f2', // Brand White (fundo suave)
                    primary200: '#e4d0ad',
                    primary500: '#CCA766', // Brand Light
                    primary600: '#BC8E38', // BRAND PRINCIPAL
                    primary700: '#766541', // Brand Dark (Hover)

                    // Botões de Ação
                    buttonPrimary100: '#fcf2f2',
                    buttonPrimary500: '#CCA766',
                    buttonPrimary600: '#BC8E38', // Cor do botão Salvar
                    buttonPrimary700: '#766541', // Cor do botão ao passar o mouse

                    neutral0: '#ffffff',  // Fundo dos cards/inputs (Branco puro para contraste)
                    neutral100: '#fcf2f2', // Fundo principal da tela (Seu Brand White)
                    neutral150: '#e4d0ad', // Bordas e divisórias sutis (Seu Brand Light suave)
                    neutral200: '#e4d0ad', // Bordas de inputs
                },
            },
            // Tema Escuro (Dark Mode)
            dark: {F
                colors: {
                    // Cor Principal no modo escuro
                    primary100: '#1d0f0b', // Brand Black
                    primary200: '#766541',
                    primary500: '#BC8E38',
                    primary600: '#EFA906', // Accent (Amarelo mais vivo para destaque no escuro)
                    primary700: '#CCA766',

                    // Botões no modo escuro
                    buttonPrimary100: '#fcf2f2',
                    buttonPrimary500: '#CCA766',
                    buttonPrimary600: '#EFA906', // Botão bem vivo
                    buttonPrimary700: '#BC8E38',

                    neutral0: '#150a08',    // Fundo dos cards (Um pouco mais escuro que o brand black para profundidade)
                    neutral100: '#1d0f0b',  // Fundo principal da tela (Seu Brand Black)
                    neutral150: '#3b1f18',  // Bordas sutis
                    neutral200: '#766541',  // Bordas mais visíveis (Seu Brand Dark)
                    neutral800: '#fcf2f2',  // Cor do Texto principal no modo escuro
                },
            }
        },
    },
    bootstrap(app) {
        console.log(app);
    },
};